#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-rag"
compatibility_date = "2024-08-21"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "cloudflare-rag-index"

[[d1_databases]]
binding = "DB"                                       
database_name = "cloudflare-rag"
database_id = "c3eb53bf-1c29-47eb-8f68-dea3136d8e71" # replace with your database id
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cloudflare-rag-bucket"

[[kv_namespaces]]
binding = "rate_limiter"
id = "2df3c41a44e34da491868123cf437c89" # replace with your KV id
